version: '3.8'

services:
  db:
    image: postgres:13
    container_name: ebd_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-ebd}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ebd_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ebd_backend
    command: /start-reload.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-ebd}
      - PYTHONUNBUFFERED=1
    networks:
      - ebd_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ebd_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_HOST=localhost:8000
    networks:
      - ebd_network

volumes:
  postgres_data:

networks:
  ebd_network:
    driver: bridge
